# Generated by Django 2.2.11 on 2020-04-12 03:21

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
