# Generated by Django 2.2 on 2021-08-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_time',
            field=models.DateTimeField(),
        ),
    ]
